### ISSUE TITLE
 cnpm start 报错

### ISSUE THREAD

**Issue by manyhelp** [lqqyt2423/wechat_spider#38] opened 2019-08-01 08:36 UTC
$ cnpm start

> wechat_spider@1.1.1 start E:\wechat_spider\wechat_spider
> DEBUG=ws:* NODE_ENV=production node index.js

'DEBUG' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechat_spider@1.1.1 start: `DEBUG=ws:* NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechat_spider@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-08-01T08_18_10_350Z-debug.log

**Comment by lqqyt2423** [comment] 2020-01-11 11:43
Duplicate of #39

**Closed** 2020-10-14 11:25 UTC
